target 'Crary', :exclusive => true do
  pod "Crary", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Crary", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
